//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int SpaceID { get; set; }
        public System.DateTime BookingTime { get; set; }
        public string EmailGust { get; set; }
        public string Status { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual User User { get; set; }
    }
}
