//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int CheckInOutID { get; set; }
        public int CarID { get; set; }
        public int SpaceID { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public decimal TotalCost { get; set; }
        public string Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
    }
}
